version: '3.4'

services:
  new-api:
    image: calciumion/new-api:latest
    # build: .
    container_name: new-api
    restart: always
    command: --log-dir /app/logs
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./logs:/app/logs
    environment:
      - SQL_DSN=root:123456@tcp(host.docker.internal:3306)/new-api # 修改此行，或注释掉以使用 SQLite 作为数据库
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string # 修改为随机字符串
      - TZ=Asia/Shanghai
    #      - NODE_TYPE=slave  # 多机部署时从节点取消注释该行
    #      - SYNC_FREQUENCY=60  # 需要定期从数据库加载数据时取消注释该行
    #      - FRONTEND_BASE_URL=https://openai.justsong.cn  # 多机部署时从节点取消注释该行

    depends_on:
      - redis
    healthcheck:
      test: [ "CMD-SHELL", "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  midjourney:
    image: registry.cn-shenzhen.aliyuncs.com/houhou/midjourney-proxy:latest
    restart: always
    container_name: mjopen
    user: root
    volumes:
      - ./mjopen/logs:/app/logs:rw
      - ./mjopen/data:/app/data:rw
      - ./mjopen/attachments:/app/wwwroot/attachments:rw
      - ./mjopen/ephemeral-attachments:/app/wwwroot/ephemeral-attachments:rw
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    ports:
      - '3001:8080'
    environment:
      TZ: Asia/Shanghai # 设置时区

  midjourney-mongo:
    image: mongo:latest
    container_name: midjourney-mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - ./mjopen/mongo/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user***
      MONGO_INITDB_ROOT_PASSWORD: password***

  midjourney-web:
    image: registry.cn-shenzhen.aliyuncs.com/houhou/chatgpt-web-midjourney-proxy:latest
    container_name: midjourney-web
    restart: always
    ports:
      - '3002:3002'
    environment:
      OPENAI_API_BASE_URL: http://new-api:3000
      OPENAI_API_KEY: password***
      OPENAI_API_MODEL: gpt-4o-mini
      MJ_SERVER: https://api.openai-hk.com
      MJ_API_SECRET: password***
      SUNO_SERVER: https://api.openai-hk.com
      SUNO_KEY: password***
      AUTH_SECRET_KEY: perfect***
      AUTH_SECRET_ERROR_COUNT: 3
      AUTH_SECRET_ERROR_TIME: 10
      API_UPLOADER: 1
      UPLOAD_TYPE: R2
      LUMA_SERVER: https://api.openai-hk.com
      LUMA_KEY: password***
      R2_DOMAIN: mj-r2.houhoukang.com
      R2_BUCKET_NAME: midjourney
      R2_ACCOUNT_ID: xxx
      R2_KEY_ID: xxx
      R2_KEY_SECRET: xxx

  wechat-server:
    image: registry.cn-shenzhen.aliyuncs.com/houhou/wechat-server:latest
    container_name: wechat-server
    restart: always
    ports:
      - "3003:3000"
    volumes:
      - ./wechat-server/data:/data
